_target_: src.model.retnet.RetNet
_partial_: True
dim: 4096
depth: 8
dim_ff_hidden: 8192
inner_dim: 32
num_head: 8
chunk_size: 512
dropout: 0.1
dtype:
  _target_: hydra.utils.get_object
  path: torch.float